Homework 05
Otus-DevOps-2017-11/vv_volkov_infra pull request #1
Opened 2017-12-21 19:51 UTC by chupacabra007

no comments

2017-12-22 11:59 UTC, Nklya requested changes
1. Виктор, подключение к твоему VPN не работает.
Ты сам его проверял?
Порт открыт?
2. Описание PR нужно заполнять. Хотя бы "Выполнено ДЗ №5"
<img width="718" alt="screen shot 2017-12-22 at 14 53 57" src="https://user-images.githubusercontent.com/26086394/34297287-5a8f3588-e728-11e7-8539-323520d9b9db.png">
3. Коммиты у тебя в репозиторий идут видимо не под тем пользователем, который зарегестрирован на GitHub, в итоге они показываются вот так:
<img width="1019" alt="screen shot 2017-12-22 at 14 53 34" src="https://user-images.githubusercontent.com/26086394/34297339-9f39969c-e728-11e7-85b3-a81be3121c06.png">

Плюс, имя для гита нужно настроить полностью.

2017-12-22 17:55 UTC, Nklya commented
Его не нужно закрывать

2017-12-22 17:56 UTC, Nklya commented
В PR можно добавлять изменения добавляя коммиты в ветку

2017-12-22 18:11 UTC, chupacabra007 commented
Ок. По ошибке закрыл PR.

2017-12-24 11:02 UTC, Nklya approved these changes
Добрый день.

Виктор, условия ДЗ выполнены, описание в ридми добавлено верное, VPN работает.

Единственное, что стоит упомянуть, что начиная с OpenSSH_7.3p1 можно использовать директиву ProxyJump вместо ProxyCommand
https://wiki.gentoo.org/wiki/SSH_jump_host#Setup_2

Не забудь удалить хосты и постоянный IP адрес.

2017-12-24 11:14 UTC, merged